export type Artwork = {
  accession_number: string;
  artist: string;
  classification: string;
  continent: string;
  country: string;
  creditline: string;
  culture: string | null;
  curator_approved: number;
  dated: string;
  department: string;
  description: string;
  dimension: string;
  id: number | string;
  image: string;
  image_copyright: string | null;
  image_height: number | '';
  image_width: number | '';
  inscription: string | null;
  life_date: string;
  markings: string | null;
  medium: string;
  nationality: string;
  object_name: string | null;
  portfolio: string | null;
  provenance: string | null;
  restricted: number;
  rights_type: string;
  room: string;
  signed: string | null;
  style: string | null;
  text: string | null;
  title: string;
};

export type DocToLLM = {
  artist: string;
  classification: string;
  continent: string;
  country: string;
  dated: string;
  id: number | string;
  source: string;
  chunk: string;
};
